### ISSUE TITLE
Unable to build using visual studio 2008

### ISSUE THREAD

**Issue by rahultechie** [libyal/libesedb#10]
I have downloaded the zip file which contains all the source code. When I open the solution file in visual studio 2008, and start building the solution, I get lot of errors. Am I missing something ?

**Comment by joachimmetz** [comment]
Yes, don't use the zip file, this is github version of the version in git. Github doesn't allow me to turn off this functionality. So you either follow the additional instructions for the source from git: https://github.com/libyal/libesedb/wiki/Building#git

Or grab the `make dist` version of the source from: https://github.com/libyal/libesedb/releases named: libesedb-experimental-20141110.tar.gz
