### ISSUE TITLE
esedbexport -T with unexistent table

### ISSUE THREAD

**Issue by azerg** [libyal/libesedb#14]
I'm not sure this is an issue and worth seeing)) Exporting table by name, that doesnt exists, produces successful message and no output (as expected :D)

How to reproduce: 
``` 
esedbexport.exe -T lalalainvalidname WebCacheV01.dat
```
Actual behavior: 
Output is:
> esedbexport 20150409
> Opening file.
> Export completed.

Expected behavior: 
Smth that tells that this table doesnt exists in defined database.

**Comment by joachimmetz** [comment]
I'll have a look when time permits.

**Comment by joachimmetz** [comment]
Confirmed. This is largely a UX bug, I'll make some changes.
