### ISSUE TITLE
Unable to successfull run make on Cygwin

### ISSUE THREAD

**Issue by steven-platt** [libyal/libesedb#15]
I was getting the OOM thing in Kali so I'm trying in Cygwin.

After installing all the required packages, running ./synclibs.sh, ./autogen.sh and ./configure, I get the following when I run make:

```
libtool: link: gcc -g -O2 -Wall -o .libs/esedbexport.exe esedbexport.o esedboutput.o exchange.o export.o export_handle.o log_handle.o webcache.o windows_search.o windows_security.o  ../libcsystem/.libs/libcsystem.a ../libfmapi/.libs/libfmapi.a ../libfvalue/.libs/libfvalue.a ../libfwnt/.libs/libfwnt.a ../libfguid/.libs/libfguid.a ../libfdatetime/.libs/libfdatetime.a ../libcfile/.libs/libcfile.a ../libcpath/.libs/libcpath.a ../libuna/.libs/libuna.a ../libcsplit/.libs/libcsplit.a ../libesedb/.libs/libesedb.dll.a ../libcnotify/.libs/libcnotify.a ../libclocale/.libs/libclocale.a ../libcerror/.libs/libcerror.a ../libcstring/.libs/libcstring.a -lintl -L/usr/local/lib
../libcnotify/.libs/libcnotify.a(libcnotify_verbose.o): In function `libcnotify_verbose_set':
/home/ttalap/libesedb/libcnotify/libcnotify_verbose.c:36: multiple definition of `libcnotify_verbose_set'
../libesedb/.libs/libesedb.dll.a(d000265.o):(.text+0x0): first defined here
../libclocale/.libs/libclocale.a(libclocale_codepage.o): In function `libclocale_codepage_copy_from_string':
/home/ttalap/libesedb/libclocale/libclocale_codepage.c:130: multiple definition of `libclocale_codepage_copy_from_string'
../libesedb/.libs/libesedb.dll.a(d000250.o):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
Makefile:725: recipe for target 'esedbexport.exe' failed
make[1]: *** [esedbexport.exe] Error 1
make[1]: Leaving directory '/home/ttalap/libesedb/esedbtools'
Makefile:768: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by joachimmetz** [comment]
I'll have a look when time permits. It looks like an issue with libtool behaving differently on Cygwin.

**Comment by kempy007** [comment]
../libcnotify/.libs/libcnotify.a(libcnotify_verbose.o): In function `libcnotify_ verbose_set':
/home/Administrator/libesedb/libcnotify/libcnotify_verbose.c:36: multiple defini tion of `libcnotify_verbose_set'
../libesedb/.libs/libesedb.dll.a(d000258.o):(.text+0x0): first defined here
../libclocale/.libs/libclocale.a(libclocale_codepage.o): In function `libclocale _codepage_copy_from_string':
/home/Administrator/libesedb/libclocale/libclocale_codepage.c:130: multiple defi nition of `libclocale_codepage_copy_from_string'
../libesedb/.libs/libesedb.dll.a(d000243.o):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:750: esedbexport.exe] Error 1
make[1]: Leaving directory '/home/Administrator/libesedb/esedbtools'
make: *** [Makefile:796: all-recursive] Error 1

Bump Same issue....

**Comment by kempy007** [comment]
Solved! please update documentation for cygwin instructions to include 
./configure --enable-static-executables=yes  --enable-shared=no
make
make install

**Comment by joachimmetz** [comment]
@kempy007 thanks for your findings but this is a work around and not a fix

**Comment by joachimmetz** [comment]
`-D_WIN32` is not set, which causes means `LIBESEDB_DLL_EXPORT` is not set and the functions are not correctly exported for the linkage. Made change in https://github.com/libyal/libesedb/commit/1a2fb91338f39f18542dafed43200ca2cad745c2 that should solve this issue.
