### ISSUE TITLE
Killed! after a while until memory is full

### ISSUE THREAD

**Issue by Beast141** [libyal/libesedb#18]
Hi, having an issue with your latest version - 20160128 from a gitpull.

When i use this command to extract:
esedbexport -l /tmp/esedbexport.log -t /tmp/ntds.dit.export <ntds.dit file>

After a while it gets killed on datatable 5 of 13.

I have discovered it is eating up all the memory and then it just dies.
I had 2GB in my VM Kali.
I then increased the VM to 12GB. and after a while it completed without errors. but i was monitoring the memory on the VM, it went to almost 100% just before a 140MB ntds.dit file finished.  For larger files i guess you would need more memory to finish the job. 

Is it correct in saying that i shouldve used this alpha version instead?
http://pkgs.fedoraproject.org/repo/pkgs/libesedb/libesedb-alpha-20120102.tar.gz/198a30c98ca1b3cb46d10a12bef8deaf/

Do you have any other latest alpha versions? because in your downloads section I only see 2 experimental ones.

Thank you for such amazing work btw.!

**Comment by joachimmetz** [comment]
Memory consumption on large database files is a known issue: https://github.com/libyal/libesedb/issues/2

> Do you have any other latest alpha versions?
No, I'll try to get to releasing one, if time permits.

Marking this as a duplicate https://github.com/libyal/libesedb/issues/3
