### ISSUE TITLE
esedbexport getting killed

### ISSUE THREAD

**Issue by lukewatson01** [libyal/libesedb#19]
Exporting table 1 (MSysObjects) out of 11.
Exporting table 2 (MSysObjectsShadow) out of 11.
Exporting table 3 (MSysUnicodeFixupVer2) out of 11.
Exporting table 4 (datatable) out of 11.
Killed.

My ntds.dit file is approximately 443mb , is there a reason why it is getting killed. My Kali linux was using 3gm of ram and an i7 3610qm

**Comment by joachimmetz** [comment]
Likely a duplicate of: https://github.com/libyal/libesedb/issues/3

**Comment by joachimmetz** [comment]
I'll have a look as soon as time permits.

**Comment by lukewatson01** [comment]
Oh ok thx!
