### ISSUE TITLE
Unable to build: git version contains older libcfile.m4

### ISSUE THREAD

**Issue by thallfe** [libyal/libesedb#20]
I am unable to build using Yosemite, I have followed the build instructions but when I come to make I get the following error:

libcfile/libcfile_support.c:742:2: error: Missing file remove function
#error Missing file remove function
 ^
1 error generated.

**Comment by joachimmetz** [comment]
Try one of the distribution packages: https://github.com/libyal/libesedb/releases

E.g. https://github.com/libyal/libesedb/releases/download/20151213/libesedb-experimental-20151213.tar.gz 

I looks like there might be a platform incompatibility in libcfile for OSX

**Comment by lld0227** [comment]
Linux kali 4.3.0-kali1-amd64 #1 SMP Debian 4.3.3-5kali4 (2016-01-13) x86_64 GNU/Linux

I'm running Kali 2016 amd64, having the same issue, downloaded the 20151213, but same issue

libcfile_support.c:742:2: error: #error Missing file remove function
 #error Missing file remove function
 ^

**Comment by joachimmetz** [comment]
I'll have a look as soon as time permits.

**Comment by thallfe** [comment]
I've managed to get a working build now, downloaded the file "https://github.com/libyal/libesedb/releases/download/20151213/libesedb-experimental-20151213.tar.gz" and compiled as a pkg file.

**Comment by glindner** [comment]
thallfe, thank you for that version suggestion. That worked for my situation! I am also running Kali 2016 release and had the described issue. I can now get smbexec to install without complaint, which is great!

**Comment by juushya** [comment]
Same issue here seen on Ubuntu 12.04 amd64. 
Using libesedb-experimental-20151213.tar.gz package.

`libcfile_support.c:742:2: error: #error Missing file remove function`

**Comment by joachimmetz** [comment]
This has to do that libcfile.m4 has not yet been updated. Unless you are actively developing libesedb using the packaged version is recommended.

**Comment by juushya** [comment]
Just checked it with 20151213.zip. Throws same error..

**Comment by joachimmetz** [comment]
That is not a packaged version, that is export functionality of github and cannot be turned off, last time I checked.

A packaged version is the result of `make dist`.

**Comment by juushya** [comment]
I see, but not sure I follow on next steps. 

I got the 20151213 & 20151205.zip, extracted, and ran this:

```
./synclibs.sh
./autogen.sh
./configure
```
All works fine till here.

`make` throws the error. But `make dist` creates libesedb-20151213.tar.gz.

What next?

**Comment by joachimmetz** [comment]
A packaged version provided by the project. If you think you need to make a point with your coments I suggest spending that time and energy to send a PR instead.

**Comment by juushya** [comment]
Hey joachimmetz, I didn't imply anything else. I am sorry if you found my comment offending.! I really wasn't sure what to do next to have this set up.

**Comment by joachimmetz** [comment]
Thx for the clarification. 

> I didn't imply anything else. I am sorry if you found my comment offending.

I did not say that, it could be interpreted in multiple ways. And was being verbose with "If" this is the case, there are more effective ways to do so.

> I really wasn't sure what to do next to have this set up.

Download: libesedb-experimental-20151213.tar.gz from https://github.com/libyal/libesedb/releases as indicated on: https://github.com/libyal/libesedb/wiki/Building#source-package

I'll get a fix in for the version in git as soon as time permits.

**Comment by joachimmetz** [comment]
libcfile.m4 update, issue should be solved now.
