### ISSUE TITLE
Cannot build using MinGW

### ISSUE THREAD

**Issue by sdrtgdszhdfzhdf** [libyal/libesedb#21]
I tried both Sections in https://github.com/libyal/libesedb/wiki/Building:
"Using Minimalist GNU for Windows (MinGW)" and "Using MSYS-MinGW"
(Yes, I use the msys shell and not the native Windows shell)

The problem is
" ./configure . No such file or directory"

make reports that no makefile is present, even though makefile.am is in the directory.

**Comment by joachimmetz** [comment]
Use the source package or follow the instructions on how to create the configure script: https://github.com/libyal/libesedb/wiki/Building#git

**Comment by sdrtgdszhdfzhdf** [comment]
Thank you for your answer.
You mean the source package of "libesedb" ?
where do I find that? I just downloaded "libesedb-master"

**Comment by joachimmetz** [comment]
> I just downloaded "libesedb-master"

That's not it.

From: https://github.com/libyal/libesedb/wiki/Building#source-package
```
To retrieve the source package go to the downloads page and download the file named:

libesedb-alpha-<version>.tar.gz
```

See actual wiki page for the link.

**Comment by sudofly** [comment]
I'm also having problems using msys when running make I get:

```
libcfile_file.c:3670:17: error: macro "__IOCTL_DISK_" requires 3 arguments, but
only 2 given
                 IOCTL_DISK_GET_LENGTH_INFO,
                 ^
In file included from c:\mingw\include\winioctl.h:55:0,
                 from libcfile_file.c:51:
libcfile_file.c:3670:17: error: '__IOCTL_DISK_' undeclared (first use in this fu
nction)
                 IOCTL_DISK_GET_LENGTH_INFO,
                 ^
libcfile_file.c:3670:17: note: each undeclared identifier is reported only once
for each function it appears in
libcfile_file.c:3707:19: error: macro "__IOCTL_DISK_" requires 3 arguments, but
only 2 given
                   IOCTL_DISK_GET_DRIVE_GEOMETRY,
                   ^
make[1]: *** [libcfile_file.lo] Error 1
make[1]: Leaving directory `/MinGW/libesedb-20151205/libcfile'
make: *** [all-recursive] Error 1
```

**Comment by joachimmetz** [comment]
@sudofly which Windows API version (WINVER) ?

**Comment by sudofly** [comment]
i'm compiling on Windows 10 and I set the WINVER var to 0x0501 as follows:

```
WINVER=0x0501
CPPFLAGS=-DWINVER=0x0501 ./configure --prefix=/mingw
```

- is that the right way to do it?

**Comment by joachimmetz** [comment]
> is that the right way to do it?

Yes, however the issue seems to be somewhere else: c:\mingw\include\winioctl.h

IOCTL_DISK_GET_LENGTH_INFO is just a convenience macro for CTL_CODE

See: https://github.com/libyal/libcfile/blob/584847b4957874d49ce19944d59bc5c090344f31/libcfile/libcfile_file.c#L3591

```
error: '__IOCTL_DISK_' undeclared (first use in this function)
```

Indicates that something has changed within the MinGW definitions.

**Comment by sudofly** [comment]
hmm.. we are wandering out of my skillset now :-)

is there a better way I can compile a windows executable, or even better somewhere where I can download pre-built binaries ?

Thanks

**Comment by joachimmetz** [comment]
> is there a better way I can compile a windows executable

Use Visual Studio

> even better somewhere where I can download pre-built binaries ?

Not officially, the project status is experimental and a single person effort, maintaining binary builds, especially for Windows, it too time consuming.

**Comment by sudofly** [comment]
> Not officially, the project status is experimental and a single person effort, maintaining binary builds, especially for Windows, it too time consuming.


case and point I guess!

I'll try and find an instance of VB and build from there. Cheers all!
