### ISSUE TITLE
LNK2019

### ISSUE THREAD

**Issue by DazzzzedMan** [libyal/libesedb#22]
I built the libraries via msvcpp solution, but when I call any function (even libesedb_file_initialize(..)) I receive LNK2019 error. All the libs are linked to the project.

**Comment by joachimmetz** [comment]
Did you close this out of mistake or did you solve the issue yourself?

**Comment by DazzzzedMan** [comment]
**Libcthreads** project wasn't compiled succesfully because WINVER value is more than 0x0601 in my case. I just defined WINVER 0x0601.
