### ISSUE TITLE
esedbdumphash

### ISSUE THREAD

**Issue by nikola7** [libyal/libesedb#24]
Hello. I don't search esedbdumphash in last version libesedb. Old version can't dump big file 500Mb 
error:
Opening file.
Dumping from table 4 (datatable).
Error
Unable to export file.
libfvalue_value_copy_to_32bit: entry data size out of bounds.
libesedb_record_get_value_32bit: unable to copy value to 32-bit value.
export_handle_export_record_is_needed_for_hash: unable to retrieve value.
export_handle_export_table: unable to export record.
export_handle_export_file: unable to export table: 3.

**Comment by joachimmetz** [comment]
I have not clue what you are trying to tell me, can you explain your problem a bit more clear?

**Comment by joachimmetz** [comment]
Not actionable, and no update from OP, closing issue. Reopen if needed.
