### ISSUE TITLE
does it support excahange 2013 edb file

### ISSUE THREAD

**Issue by jacabsmith** [libyal/libesedb#25]
hello does libesedb supported exchange 2013 file format

**Comment by joachimmetz** [comment]
Depends what you are specifically asking.

The library should support the ESE database format, it does not support the MAPI database on top of the ESE layer.

**Comment by joachimmetz** [comment]
Nor does the library support handling large edb files, which exchanges ones typically are.

**Comment by jacabsmith** [comment]
How to decode exchange 2013 file format. can you help us.

**Comment by jacabsmith** [comment]
how to use this library in 2013 edb file

**Comment by jacabsmith** [comment]
how to use this library in 2013 edb file

**Comment by jacabsmith** [comment]
any help to decode 2013 edb file

**Comment by joachimmetz** [comment]
What help do you need? If you're not familiar with file format analysis I can provide you little help. I lack the time to do much work on the library and Exchange support at this time.

**Comment by jacabsmith** [comment]
I can not read the mail body in any mail how to i read

**Comment by jacabsmith** [comment]
I can not read the mail body in any mail how to i read edb 2013 file

**Comment by joachimmetz** [comment]
libesedb will provide you only access to the ESE layer the MAPI DB layer you'll have to figure out yourself.
