### ISSUE TITLE
test_library.sh fails on some 32bit architectures

### ISSUE THREAD

**Issue by hillu** [libyal/libesedb#26]
On Debian's [armel](https://buildd.debian.org/status/fetch.php?pkg=libesedb&arch=armel&ver=20170121-1&stamp=1485088795&raw=0),  [armhf](https://buildd.debian.org/status/fetch.php?pkg=libesedb&arch=armhf&ver=20170121-1&stamp=1485090789&raw=0),  [i386](https://buildd.debian.org/status/fetch.php?pkg=libesedb&arch=i386&ver=20170121-1&stamp=1485086950&raw=0),  [hppa](https://buildd.debian.org/status/fetch.php?pkg=libesedb&arch=hppa&ver=20170121-1&stamp=1485098630&raw=0),  [powerpc](https://buildd.debian.org/status/fetch.php?pkg=libesedb&arch=powerpc&ver=20170121-1&stamp=1485087066&raw=0),  [x32](https://buildd.debian.org/status/fetch.php?pkg=libesedb&arch=x32&ver=20170121-1&stamp=1485087624&raw=0)  autobuilders, the tests fail with

    esedb_test_data_segment.c:135 result (1) != -1
    Unable to run test: libesedb_data_segment_initialize
    Testing: data_segment  (FAIL)

**Comment by joachimmetz** [comment]
Any information in tests/test-suite.log that indicates why the test is failing?

**Comment by joachimmetz** [comment]
https://github.com/libyal/libesedb/blob/master/tests/esedb_test_data_segment.c#L127

At first glance this looks like the bounds check is missing in:
https://github.com/libyal/libesedb/blob/b5abe2d05d5342ae02929c26475774dbb3c3aa5d/libesedb/libesedb_data_segment.c#L38

I've added it in https://github.com/libyal/libesedb/commit/0eb2efbc87440772726eab943c3762eaf1ed1c1e

if this is still failing, and to get more details, try running:
```
make check CHECK_WITH_STDERR=1;
```

**Comment by hillu** [comment]
* Joachim Metz:

> I've added it in 0eb2efb

Hi Joachim,

with your patch, my build passes on i386. Thanks.

Cheers,
-Hilko

**Comment by hillu** [comment]
According to https://buildd.debian.org/status/package.php?p=libesedb, libesedb can now again be built on all the architectures. Thank you.
