### ISSUE TITLE
Documentation Mistake

### ISSUE THREAD

**Issue by s1syphu5** [libyal/libesedb#32]
Hi,

I didn't use the library but looked at the documentation and found a mistake.

At the database header at offset 104 it suppose to be the database ID (4 bytes) and then the log signature (28 bytes).

I'm not sure but I compared the header with the dump of eseutil.exe, and it makes sense.

**Comment by joachimmetz** [comment]
Thx, for the report I'll have a look as soon as time permits

**Comment by joachimmetz** [comment]
Confirmed, thx for flagging.

**Comment by joachimmetz** [comment]
Addressed in https://github.com/libyal/libesedb/commit/eaf1f9d810c200a382cf207401d41677bdad0816
