### ISSUE TITLE
autogen failing

### ISSUE THREAD

**Issue by jonbelanger** [libyal/libesedb#33]
I've cloned latest but getting the following.

$ ./autogen.sh 
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
configure.ac:35: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
configure.ac:35: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
configure.ac:35: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
configure.ac:205: error: required file 'libcerror/Makefile.in' not found
configure.ac:206: error: required file 'libcthreads/Makefile.in' not found
configure.ac:207: error: required file 'libcdata/Makefile.in' not found
configure.ac:208: error: required file 'libclocale/Makefile.in' not found
configure.ac:209: error: required file 'libcnotify/Makefile.in' not found
configure.ac:210: error: required file 'libcsplit/Makefile.in' not found
configure.ac:211: error: required file 'libuna/Makefile.in' not found
configure.ac:212: error: required file 'libcfile/Makefile.in' not found
configure.ac:213: error: required file 'libcpath/Makefile.in' not found
configure.ac:214: error: required file 'libbfio/Makefile.in' not found
configure.ac:215: error: required file 'libfcache/Makefile.in' not found
configure.ac:216: error: required file 'libfdata/Makefile.in' not found
configure.ac:217: error: required file 'libfdatetime/Makefile.in' not found
configure.ac:218: error: required file 'libfguid/Makefile.in' not found
configure.ac:219: error: required file 'libfvalue/Makefile.in' not found
configure.ac:220: error: required file 'libfwnt/Makefile.in' not found
configure.ac:225: error: required file 'libfmapi/Makefile.in' not found
configure.ac:226: error: required file 'libmapidb/Makefile.in' not found
Makefile.am:3: error: required directory ./libcerror does not exist
Makefile.am:3: error: required directory ./libcthreads does not exist
Makefile.am:3: error: required directory ./libcdata does not exist
Makefile.am:3: error: required directory ./libclocale does not exist
Makefile.am:3: error: required directory ./libcnotify does not exist
Makefile.am:3: error: required directory ./libcsplit does not exist
Makefile.am:3: error: required directory ./libuna does not exist
Makefile.am:3: error: required directory ./libcfile does not exist
Makefile.am:3: error: required directory ./libcpath does not exist
Makefile.am:3: error: required directory ./libbfio does not exist
Makefile.am:3: error: required directory ./libfcache does not exist
Makefile.am:3: error: required directory ./libfdata does not exist
Makefile.am:3: error: required directory ./libfdatetime does not exist
Makefile.am:3: error: required directory ./libfguid does not exist
Makefile.am:3: error: required directory ./libfvalue does not exist
Makefile.am:3: error: required directory ./libfwnt does not exist
Makefile.am:3: error: required directory ./libfmapi does not exist
Makefile.am:3: error: required directory ./libmapidb does not exist
autoreconf: automake failed with exit status: 1

$ automake --version
automake (GNU automake) 1.14.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.

$ autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.

**Comment by joachimmetz** [comment]
You need to run `./synclibs.sh` first. Also see: https://github.com/libyal/libesedb/wiki/Building#git
