### ISSUE TITLE
[BTA] libesdb_record_get_long_value: unable to create long value

### ISSUE THREAD

**Issue by 3ldidi94** [libyal/libesedb#35]

**Comment by joachimmetz** [comment]
@3ldidi94 I must have missed this earlier, if you want this issue to be solved please provide more information such as:

* a description of the problem
* version of libesedb
* how libesedb was build (platform, compiler)
* what command and file generated the error

Basically any information relevant to trying to determine the cause of the error message

**Comment by 3ldidi94** [comment]
@joachimmetz Thanks for your help ! I have solved the issue. It was a bad extraction of ESE database (ntds.dit) I think the DB was corrupted so I export the DB once more and everything worked perfectly

**Comment by joachimmetz** [comment]
thanks for confirming
