### ISSUE TITLE
Make fails with fatal error libfvalue_split_string.h: no such file or directory.

### ISSUE THREAD

**Issue by itec285** [libyal/libesedb#38]
Hi, I apologize if this is a dumb question.  Trying to compile today on Kali Linux 2017.3 64 bit, at the end of the make process I am getting the following error: 
"
In file included from libesedb_data_definition.c:39:0:
libesedb_libfvalue.h:36:10: Fatal Error: libfvalue_split_string.h: No such file or directory
  #include <libfvalue_split_string.h>
compilation terminated

Any ideas where I can get this file?  Thanks very much.

![capture2](https://user-images.githubusercontent.com/17221442/35474371-b40eb320-034a-11e8-9c73-258313ac8479.PNG)

**Comment by joachimmetz** [comment]
You are trying to build from git this is not recommended unless you're developing libesedb, see https://github.com/libyal/libesedb/wiki/Building

Regarding the issue you're seeing this is work in progress, libesedb_libfvalue.h needs to updated to work with the lastest libfvalue version.

**Comment by joachimmetz** [comment]
libfvalue issue should be addressed in https://github.com/libyal/libesedb/commit/6c4786346b2bc0873bb43ec66e56a75894a9dc6c

**Comment by itec285** [comment]
Thanks Joachim, I am relatively new to github and did not realize this.  I
will take your advice and try the steps on the linked page.  Thanks again
for your email, and your work on this project!

Mike
