### ISSUE TITLE
esedbexport will not run on Kali

### ISSUE THREAD

**Issue by nabargar** [libyal/libesedb#41]
I installed the libesedb 20170121 following the install document in the archive.  After the install, when I am trying to run the 'esedbexport -m tables /ntds.dit' I am receiving the below error. (I can't get a screenshot since this is running on a standalone system that I cannot connect to my production network)  Was this an incorrect install or am I likely missing something or not seeing an error during the install?

esedbexport: error while loading shared libraries: libesedb.so.1: cannot open shared object file: No such file or directory

**Comment by joachimmetz** [comment]
make sure your shared library cache is updated, on most modern Linux run `ldconfig`, otherwise make sure you library path is correct

**Comment by nabargar** [comment]
Thank You, that seems to have worked.  It's now appearing to run.

**Comment by saadg3989** [comment]
> I installed the libesedb 20170121 following the install document in the archive. After the install, when I am trying to run the 'esedbexport -m tables /ntds.dit' I am receiving the below error. (I can't get a screenshot since this is running on a standalone system that I cannot connect to my production network) Was this an incorrect install or am I likely missing something or not seeing an error during the install?
> 
> esedbexport: error while loading shared libraries: libesedb.so.1: cannot open shared object file: No such file or directory


Can you help me how to install libesedb on kali any step by step command or any thing!!

**Comment by saadg3989** [comment]
sorry for commemting on it i am new in this field

i copie it on my dektop at root user dekstop now from there can tell me the
commands i can run and install it

thanks

**Comment by joachimmetz** [comment]
it is installed otherwise you're not able to run ;)

From "joachimmetz commented on May 16" (also see above)
```
make sure your shared library cache is updated, on most modern Linux run ldconfig, otherwise make sure you library path is correct
```

**Comment by saadg3989** [comment]
let me explain what i did so you can help me efficiently

I have windows server 2012 with internet access

I downloaded from the link filename libesedb-master


and then from there copied the downloaded file on my kali (no internet)

with root user login and on its desktop

Now from there tell me what i am supposed to do to make it work

please share the comands or steps

thanks

**Comment by joachimmetz** [comment]
> let me explain what i did so you can help me efficiently
>  Now from there tell me what i am supposed to do to make it work

I cannot help you.

1. I don't know kali
2. you're not reading what I'm telling you
3. the current version of libesedb is not intended for use with Active Directory databases
