### ISSUE TITLE
No get_value_data_as_binary method in pyesedb.record

### ISSUE THREAD

**Issue by lfkpoa** [libyal/libesedb#44]
Binary columns can use compression.  
Unfortunately, in Python bindings there is only a method to read the column data as raw (get_value_data), which does not decompress the data.
There are different methods to read different column types, but not as binary data with decompression.
For example, get_value_data_as_string reads the data, decompresses it if necessary, and converts to a string, but it cannot be used to read a binary column, even if we know that the content is a string.
I noticed that libesedb_record.c has the method libesedb_record_get_value_binary_data, which does exactly what I think it is missing in pyesedb_record.
I'm trying to read emails from an edb file from Exchange Server and I'm stuck with compressed binary contents that I am not able to decompress.

**Comment by joachimmetz** [comment]
> Unfortunately, in Python bindings there is only a method to read the column data as raw (get_value_data), which does not decompress the data.

The compression can be application specific or by the ESE database layer (Also see https://github.com/libyal/libesedb/blob/master/documentation/Extensible%20Storage%20Engine%20(ESE)%20Database%20File%20(EDB)%20format.asciidoc#63-compression) 

Could you provide more context (a sample file would help) if the compression in your case is application specific or something the ESE database layer should handle.

**Comment by joachimmetz** [comment]
No response from original reporter closing issue.
