### ISSUE TITLE
esedb_test_checksum tests fail on s390x (64-bit big-endian)

### ISSUE THREAD

**Issue by hillu** [libyal/libesedb#45]
While trying to build libesedb, the Debian/s390x autobuilder [failed](https://buildd.debian.org/status/fetch.php?pkg=libesedb&arch=s390x&ver=20181229-1&stamp=1547425061&raw=0) in the `libesedb_checksum_calculate_little_endian_xor32` test:
```
esedb_test_checksum.c:1237 checksum_value (1617174027) != 669295665
Unable to run test: libesedb_checksum_calculate_little_endian_xor32
Testing: checksum  (FAIL)
```

I have found some spots in `libesedb_checksum_calculate_little_endian_xor32` that look like they could use some `le32toh` or `be32toh`, but I haven't figured out what exactly is going wrong.

**Comment by joachimmetz** [comment]
I'll have a look when time permits, but there should be no need for using `le32toh` or `be32toh`

**Comment by joachimmetz** [comment]
Is a possibility, I have a look.

**Comment by joachimmetz** [comment]
updated function to support 64-bit big-endian, CI tests now pass, closing issue
