### ISSUE TITLE
get_value_data does not return expected blob?

### ISSUE THREAD

**Issue by kamnon** [libyal/libesedb#47]
When trying to parse the response header of a download record (Container 29, column 21), it appears that the returned value is incorrect (b'\x01\x00\x00\x00' instead of a large blob that can be seen using NirSoft ESEDatabaseview - https://www.nirsoft.net/utils/ese_database_view.html).

e.g.
>>> tbl = db.get_table_by_name('Container_29')
>>> lst = [raw_history_record.get_value_data(21) for raw_history_record in tbl.records]
>>> lst
[b'\x01\x00\x00\x00']

[WebCacheV01.zip](https://github.com/libyal/libesedb/files/2878902/WebCacheV01.zip)

**Comment by joachimmetz** [comment]
libesedb_record_get_value_data return the raw value data, you likely want libesedb_record_get_long_value for large values

**Comment by kamnon** [comment]
get_value_data_as_long_value returns None in this case...

**Comment by joachimmetz** [comment]
I'll have a look when time permits

**Comment by bulhakov-adf** [comment]
Hi @joachimmetz,

Just want to add some info: I also have faced this issue in the latest build(20181229). When I run esedbexport with the following [WebCacheV01](https://github.com/libyal/libesedb/files/2894226/WebCacheV01.zip) **libesedb_record_get_long_value** returns 0 for **value_entry** equals 17 with **record_iterator** equal 10 in **export_handle_export_table** function and with **table_index** equals 10 taken from **export_handle_export_table** function.

In version 20170121 everything works fine.

**Comment by bulhakov-adf** [comment]
Hi @joachimmetz,

Just want to add some info: I also have faced this issue in the latest build(20181229). When I run esedbexport with the following [WebCacheV01.zip](https://github.com/libyal/libesedb/files/2899627/WebCacheV01.zip) **libesedb_record_get_long_value** returns 0 for **value_entry** equals 17 with **record_iterator** equal 10 and with **table_index** equals 20 taken from **export_handle_export_table** function.

In version 20170121 everything works fine.

**Comment by kamnon** [comment]
I tried using version 20170121 and get_value_data_as_long_value like @bulhakov-adf , and it works 
fine for me as well.

**Comment by joachimmetz** [comment]
Finally got a chance to look into this. Running esedbexport 20181229 on the test file provided by @bulhakov-adf I get:

```
export_handle_export_long_record_value: unable to retrieve long value of record entry: 17.
export_handle_export_long_record_value: unable to retrieve long value of record entry: 21.
```

Which seems to correspond with the description. I've made some major changes in light of https://github.com/libyal/libesedb/issues/2 and tried with https://github.com/libyal/libesedb/commit/e1dbc7ace77f3072cc71e4bc4b60bdecde452662 and the issue no longer surfaces for me.

Similar for the test file created by @kamnon with esedbexport 20181229 
```
...
export_handle_export_long_record_value: unable to retrieve long value of record entry: 21.
export_handle_export_long_record_value: unable to retrieve long value of record entry: 17.
...
```

No longer surfaces with https://github.com/libyal/libesedb/commit/e1dbc7ace77f3072cc71e4bc4b60bdecde452662.

I'm closing this issue feel free to reopen if issue persists.
