### ISSUE TITLE
Any way to extract the email message from native body

### ISSUE THREAD

**Issue by Asymptot007** [libyal/libesedb#49]
native body in every message table is a large binary data..any way i can get the actual body of the email from that.

**Comment by joachimmetz** [comment]
what type of database? exchange, windows mail?

**Comment by Asymptot007** [comment]
I am trying to parse exchange server database file(.edb)..i was able to get all the tables and in message table of one of the mailbox there is a native body column which should contain the message body..but its of large binary type..any way to extract the body as string?

**Comment by joachimmetz** [comment]
This project only focuses on the underlying ESE format not the Exchange MAPI database format on top of the ESE format. Note that this differs from Exchange version to Exchange version.

**Comment by BAMSHK** [comment]
> I am trying to parse exchange server database file(.edb)..i was able to get all the tables and in message table of one of the mailbox there is a native body column which should contain the message body..but its of large binary type..any way to extract the body as string?

May I ask if this problem has been solved?
