### ISSUE TITLE
Where can I find more information about the Transaction Log Format?

### ISSUE THREAD

**Issue by likema** [libyal/libesedb#53]
In https://github.com/libyal/libesedb/blob/master/documentation/Extensible%20Storage%20Engine%20(ESE)%20Database%20File%20(EDB)%20format.asciidoc

**Transaction Log Format** is not detailed. 

Where can I get accurate **Transaction Log Format** ?

**Comment by joachimmetz** [comment]
> Where can I get accurate Transaction Log Format ?

By doing your own research.

**Comment by likema** [comment]
Thanks
