### ISSUE TITLE
[Question] Dirty database recovery support

### ISSUE THREAD

**Issue by panther142** [libyal/libesedb#55]
Hi,

Thanks for your work on the project.

I was wondering what support is available for dirty databases? 

I have tried using the Win32 API and Managed ESENT libraries on several "ditry" databases and while they can both indicate a database is dirty, they can't do anything with it until eseutil is run to recover it.

Are there any functions in your library to mimic the eseutil recover functionality? Especially when transaction logs may not be available?

Thanks

**Comment by joachimmetz** [comment]
> I was wondering what support is available for dirty databases?

best effort

> Are there any functions in your library to mimic the eseutil recover functionality? Especially when transaction logs may not be available?

Not at the moment but feel free to implement them, this is open source.

**Comment by joachimmetz** [comment]
assuming question has been answered, closing issue
