### ISSUE TITLE
Please rename %package -n libesedb-tools to esedb-tools

### ISSUE THREAD

**Issue by yecril71pl** [libyal/libesedb#57]
This package does not contain tools that deal with `libesedb`, it contains tools that deal with ESEDB itself.

**Comment by joachimmetz** [comment]
> This package does not contain tools that deal with libesedb, it contains tools that deal with ESEDB itself.

That's a matter of semantics. This package contains the tools of the libesedb project that use the libesedb library.

You can always change the spec file on your local installation, to match your naming preferences.

**Comment by yecril71pl** [comment]
> You can always change the spec file on your local installation, to match your naming preferences.

I would not have bothered you with this had I not been told it must be so because upstream has it so.  I am sorry for any inconvenience I may have caused.

**Comment by joachimmetz** [comment]
> I would not have bothered you with this had I not been told it must be so because upstream has it so.

What do you mean with upstream in this context? This project?

Then who/what is the downstream? Or who told you what about the package naming?

**Comment by yecril71pl** [comment]
openSUSE is the downstream, and the argument is we cannot change the name because everybody follows your lead.

**Comment by joachimmetz** [comment]
> the argument is we cannot change the name because everybody follows your lead.

I wish. However every distribution applies their own naming preferences. Debian seems to use `libesedb-utils` and Fedora `libesedb`. I cannot really make a default configuration for such wide ranging localized preferences.

**Comment by yecril71pl** [comment]
Well, Debian does not use `spec` files, does it?

**Comment by joachimmetz** [comment]
> Well, Debian does not use spec files, does it?

Correct, but the package also contains dpkg configuration files, that did not stop them from selecting their own naming schema.

**Comment by joachimmetz** [comment]
Closing assuming question has been answered
