### ISSUE TITLE
tab separator in exportation

### ISSUE THREAD

**Issue by patatetom** [libyal/libesedb#58]
hi Joachim,
would it be possible to use the `tabulation` character to separate fields when exporting ?
the use of the `space` character makes extraction difficult.
perhaps in the form of a parameter ? (`esedbexport -s '\t' ...`)
I couldn't put my finger on where the field separator is inserted.
regards.

**Comment by joachimmetz** [comment]
@patatetom not sure if I understand your question. Isn't tab already the value separator? (e.g. https://github.com/libyal/libesedb/blob/main/esedbtools/windows_search.c#L3153)

**Comment by patatetom** [comment]
you're absolutely right !
sorry for the inconvenience and thank you for your work 👍.

_take a good look before asking a stupid question !_
