### ISSUE TITLE
Additional information on Transaction logs

### ISSUE THREAD

**Issue by mrthaggar** [libyal/libesedb#59]
I'm trying to understand the structure of the `.log` transaction files, and whilst your (excellent) documentation provides some information, there is not really any information on how the files are structured.

Am I missing something, or this is information not provided?

**Comment by joachimmetz** [comment]
> Am I missing something, or this is information not provided?

This is to be researched / added.

**Comment by joachimmetz** [comment]
This is the current information in the documentation https://github.com/libyal/libesedb/blob/main/documentation/Extensible%20Storage%20Engine%20(ESE)%20Database%20File%20(EDB)%20format.asciidoc#8-transaction-log

**Comment by mrthaggar** [comment]
Thanks for the info.

I'm doing some research into this myself, but I'm not finding much.

Seems this is something that is handled by the esentutl application, so I'll see what I can find out.

**Comment by joachimmetz** [comment]
> Seems this is something that is handled by the esentutl application, so I'll see what I can find out.

Sounds good, let me know if you find things you want to add to the project
