### ISSUE TITLE
Super slow extraction of large NTDS.dit file

### ISSUE THREAD

**Issue by brav0hax** [libyal/libesedb#6]
root@Kali-LABS:~/esa# esedbexport 
esedbexport 20141129

Over my last 3 pentests, I have had ntds.dit files of 7.6GB, 5.3GB and 400MB.

The 400MB extracts super fast, no noticeable difference from last release. However the larger ones, if I let them run would take weeks to extract. Using the last release of libesedb it take a few hours (10 or so for the larger ones)

Not sure what has changed, but I hope you can take another look at the extraction technique.

Also, multi threading would be dope :-)

Thanks in advance.

**Comment by m-terlinde** [comment]
Hello,

I've got a question to this issue: I try to extract a 600 MB .dit with esedbexport. I've got just virtual cores (I know, there is no multithreading).
In round about 20 minutes the program just extracted 3,2 MB of the database.
Is this normal? Is it a virtualisation problem?

I use the 20151213 version.

Cheers,
Matthias

**Comment by 9Yg1rxeSeha90ZU1** [comment]
https://www.swordshield.com/2015/10/extracting-password-hashes-from-large-ntds-dit-files/

**Comment by joachimmetz** [comment]
It very nice that everyone is complaining about this but I see no contributions in terms of fixes?

**Comment by joachimmetz** [comment]
Removed off topic comments
