### ISSUE TITLE
Unsupported catalog fixed size data type 12 in version 0x620 revision 0xe6 (Windows 11)

### ISSUE THREAD

**Issue by crayy8** [libyal/libesedb#63]
We have a build of esedbexport (https://github.com/libyal/libesedb/commit/d3063656e4245ef00ca0cc2702360c743b9667d6) that is failing to process a WebCacheV01 database from a Windows 11 disk image. I've added a screenshot of the error as well as a link to download the database. If you need any additional info please let me know. 

Thanks!

![esedbexport_failure](https://user-images.githubusercontent.com/5924184/227226336-1c54148d-1451-40dc-84fb-08fc4fd86726.png)

Win11 DB: https://drive.google.com/file/d/148mMmceyj3GcNsH5tdbYNunMLGcHaxHY/view?usp=share_link

**Comment by joachimmetz** [comment]
thx for flagging I'll have a look as soon as time permits, looks like the schema was changed

**Comment by joachimmetz** [comment]
```
Table: 1			MSysObjects (2)
	Number of columns:	29
	Column	Identifier	Name	Type
	1	1	ObjidTable	Integer 32-bit signed
	2	2	Type	Integer 16-bit signed
	3	3	Id	Integer 32-bit signed
	4	4	ColtypOrPgnoFDP	Integer 32-bit signed
	5	5	SpaceUsage	Integer 32-bit signed
	6	6	Flags	Integer 32-bit signed
	7	7	PagesOrLocale	Integer 32-bit signed
	8	8	RootFlag	Boolean
	9	9	RecordOffset	Integer 16-bit signed
	10	10	LCMapFlags	Integer 32-bit signed
	11	11	KeyMost	Integer 16-bit unsigned
	12	12	LVChunkMax	Integer 32-bit signed
	13	13	PgnoFDPLastSetTime	Date and time
	14	128	Name	Text
	15	129	Stats	Binary data
	16	130	TemplateTable	Text
	17	131	DefaultValue	Binary data
	18	132	KeyFldIDs	Binary data
	19	133	VarSegMac	Binary data
	20	134	ConditionalColumns	Binary data
	21	135	TupleLimits	Binary data
	22	136	Version	Binary data
	23	137	SortID	Binary data
	24	256	CallbackData	Large binary data
	25	257	CallbackDependencies	Large binary data
	26	258	SeparateLV	Large binary data
	27	259	SpaceHints	Large binary data
	28	260	SpaceDeferredLVHints	Large binary data
	29	261	LocaleName	Large binary data
```

Looks like SortID was added

**Comment by joachimmetz** [comment]
Changes in https://github.com/libyal/libesedb/commit/16d65f060a4af64d282dced1a09664b7d95184ac

**Comment by crayy8** [comment]
Thanks for the speedy fix!

**Comment by patatetom** [comment]
will test...
thanks too JM.
