### ISSUE TITLE
About the pre-release tags

### ISSUE THREAD

**Issue by chenrui333** [libyal/libesedb#74]
👋 while [packaging the project for homebrew](https://github.com/Homebrew/homebrew-core/pull/202123), I found that the project marks all the tags as pre-release, as strong reason doing so? If that is case, when would be the tag expected to be a stable release? Thanks! (from what I see the tags seems stable and used in [many package managers](https://repology.org/project/libesedb/versions) now)

**Comment by joachimmetz** [comment]
per [README](https://github.com/libyal/libesedb/blob/main/README) this project is [experimental](https://github.com/libyal/libyal/wiki), packaging it, is at your own risk/responsibility.

**Comment by chenrui333** [comment]
yeah, totally, but I wonder if the pre-release does make sense though, as it has been widely distributed. :)

**Comment by joachimmetz** [comment]
> yeah, totally, but I wonder if the pre-release does make sense though, as it has been widely distributed. :)

Depend on what you define with pre-release, it is not a "stable" release, so pre-release would be semantically correct. Closing issue given question has been answered.
