### ISSUE TITLE
invalid tagged data type offset value out of bounds

### ISSUE THREAD

**Issue by jonnyvix** [libyal/libesedb#9]
Hello there,
I've been experimenting with the lib with both 2014 and 2015 versions and different Exchange .edb files. It seems that about all exchange 2013 files give the same error on the same data type and more or less all on the same tables.

Here's a dump with HAVE_DEBUG_OUTPUT switched on only where the error is thrown:

    esedbexport 20150522

    Opening file.
    Exporting table 29 (Folder_100).
    libesedb_data_definition_read_record: tagged data type offset data size : 20
    libesedb_data_definition_read_record: tagged data type offset data:
    00000000: 01 01 30 80 04 01 31 80  05 01 32 80 15 01 40 80   ..0...1. ..2...@.
    00000010: 18 01 79 80 01 16 83 81                            ..y.....

    libesedb_data_definition_read_record: (256) tagged data type identifier : 256
    libesedb_data_definition_read_record: (256) tagged data type offset             : 0x8018 (32792)
    Unable to export file.
    libesedb_data_definition_read_record: invalid tagged data type offset value out of bounds.
    libesedb_record_initialize: unable to read data definition record.
    libesedb_table_get_record: unable to create record.
    export_handle_export_table: unable to retrieve record: 0.
    export_handle_export_file: unable to export table: 28.

I can provide you test files if it may prove useful for debugging

**Comment by joachimmetz** [comment]
Thanks for reporting this. Test files are useful to reproduce the issue more easily.

If you don't want to upload them here and if they are small enough you can mail them otherwise maybe share them via some online storage. You can send me the details via mail.

**Comment by jonnyvix** [comment]
No problem. I'm emailing you a link for downloading the smallest edb i can find and some more info.

**Comment by joachimmetz** [comment]
Some initial changes: https://github.com/libyal/libesedb/commit/18bab34b30f6b8137f471195ce47e512cdbfca16

There seems to be an issue with finding some long values as well.

**Comment by joachimmetz** [comment]
Some changes for the long values in: https://github.com/libyal/libesedb/commit/5a4ae140fb578711d406a649dffda1b6e880bda5

**Comment by joachimmetz** [comment]
Long value changes done for now.
